# -*- coding: utf-8 -*-
"""fyp_3_podcastify_ngrok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8DVRwu1hGA82z2_k0xK5mtjpj7zn-eW
"""

#!pip install flask flask-ngrok podcastfy ipython pyngrok--quiet

#groq1=userdata.get('GROQ_API_KEY')
# IMPORTANT TO DECALRE THIS
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


#!python -m podcastfy.client --url https://www.youtube.com/watch?v=F1Wjl5PnVTY -tts edge

from pyngrok import ngrok, conf

# Set your authtoken
conf.get_default().auth_token=os.getenv("ngrok")


import os
from flask import Flask, request, jsonify, render_template_string, send_from_directory
from pyngrok import ngrok
from podcastfy.client import generate_podcast
from IPython.display import Audio, display

app = Flask(__name__)

# Define a directory to save generated audio files
AUDIO_DIR = "generated_audio"
os.makedirs(AUDIO_DIR, exist_ok=True)

def embed_audio(audio_file):
    try:
        display(Audio(audio_file))
        print(f"Audio player embedded for: {audio_file}")
    except Exception as e:
        print(f"Error embedding audio: {str(e)}")

@app.route('/')
def home():
    return '''
    <h1>Podcastify YouTube to Podcast</h1>
    <form action="/generate" method="post">
        <label for="youtube_url">YouTube URL:</label><br>
        <input type="text" id="youtube_url" name="youtube_url"><br><br>
        <input type="submit" value="Generate Podcast">
    </form>
    '''

@app.route('/generate', methods=['POST'])
def generate():
    youtube_url = request.form['youtube_url']
    try:
        audio_file_path = generate_podcast(urls=[youtube_url] ,tts_model="elevenlabs",is_local=True)#,longform=True)
        print(audio_file_path)
        # Move or copy the generated file to the static directory
        # (Assuming generate_podcast returns the full path)
        audio_file_name = os.path.basename(audio_file_path)
        static_audio_path = os.path.join(AUDIO_DIR, audio_file_name)
        # In a real application, you might want to handle file overwriting/naming collisions
        os.rename(audio_file_path, static_audio_path)


        # Construct the HTML for the audio player
        audio_html = f'''
        <h2>Podcast Generated!</h2>
        <p>Audio file: {audio_file_name}</p>
        <audio controls>
            <source src="/audio/{audio_file_name}" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
        <br>
        <a href="/">Generate another podcast</a>
        '''
        return render_template_string(audio_html)

    except Exception as e:
        return jsonify({'message': 'Error generating podcast', 'error': str(e)})

# Route to serve static audio files
@app.route('/audio/<filename>')
def served_audio(filename):
    return send_from_directory(AUDIO_DIR, filename)


if __name__ == '__main__':
    # Use 'addr' instead of 'port' for newer versions of pyngrok
    public_url = ngrok.connect(addr="5000")
    print(" * ngrok tunnel: ", public_url)
    app.run(debug=False)
#https://www.youtube.com/watch?v=lvyWndAnTyk
